name: 'EPL Action'
description: 'EPL Action'
inputs:
  some_id:  # id of input
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.some_id }}.
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash          
    - run: epl.sh
      shell: bash
